version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: 'postgres'
    stdin_open: true
    tty: true
    ports:
      - ${DATABASE_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    env_file: .env
    depends_on:
      - postgres

volumes:
  pgdata:
    external: true

