version: '3'

services:
  postgres:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres
    restart: unless-stopped
    container_name: postgres10.10-postgis2.4-lol
    volumes:
      - ${PG_DATA_HOST_PATH}:/var/lib/postgresql/data
      - ./backups:/opt/backups
    ports:
      - ${DATABASE_PORT}:5432
    env_file: .env